#
# Module manifest for module 'xkcd'
#
# Generated by: trackd
#
# Generated on: 2024-10-09
#

@{
    RootModule = 'sixkcd.psm1'
    ModuleVersion = '0.1.1'
    CompatiblePSEditions = 'Core'
    GUID = '66a7ce6d-73f5-4588-a8c8-d8b0d9105f09'
    Author = 'trackd'
    CompanyName = 'trackd'
    Copyright = '(c) trackd. All rights reserved.'
    Description = 'A module to display XKCD comics in the console using Sixel images.'
    PowerShellVersion = '7.4'
    FormatsToProcess     = 'sixkcd.format.ps1xml'
    FunctionsToExport    = 'Get-xkcd', 'Search-xkcd'
    RequiredModules      = @('Sixel')
    PrivateData          = @{
        PSData = @{
            Tags         = @(
                'Sixel',
                'Graphics',
                'Image',
                'Comic'
            )
            LicenseUri   = 'https://github.com/trackd/sixkcd/blob/main/LICENSE'
            ProjectUri   = 'https://github.com/trackd/sixkcd'
        }
    }
}
